console.log("PPPP     GGG ")
console.log("P   P   G   G")
console.log("P   P   G    ")
console.log("PPPP    G    ")
console.log("P       G  GG")
console.log("P       G   G")
console.log("P       G   G")
console.log("P        GGG ")